### ISSUE TITLE
Add support for Junit 5

### ISSUE THREAD

**Issue by ankurpathak** [arquillian/arquillian-container-tomcat#107]
Not working with Junit 5. Pls add support for Junit 5

**Comment by hantsy** [comment]
It is working well with JUnit 5, check my starter template project.

**Comment by rhusar** [comment]
This should be working fine with Junit 5 as @hantsy points out. 

Should you have a specific problem please open a new issue with more info.

Thanks @ankurpathak and @hantsy !
