### ISSUE TITLE
Support for embedded Tomcat for EE 10

### ISSUE THREAD

**Issue by manovotn** [arquillian/arquillian-container-tomcat#117]
Tomcat has version 10.1 which seems to be EE 10 oriented.
There are some Jakarta EE dependency updates, as well as updates and potential changes to Tomcat APIs.

We can either update existing module or create a new one.
Personally, I wouldn't mind updating existing one because EE 99 setup isn't as interesting (having only the namespace change, it was basically just a stepping stone for EE 10).

**Comment by starksm64** [comment]
Right EE9 is essentially just a preview release.

**Comment by starksm64** [comment]
Ok, also assigned to you. Let me know when I should to a release.

**Comment by manovotn** [comment]
Sure, thanks :)
