### ISSUE TITLE
Push Tomcat container to maven central

### ISSUE THREAD

**Issue by arjantijms** [arquillian/arquillian-container-tomcat#126]
There's only an old alpha version of the Tomcat container available on Maven central:

https://mvnrepository.com/artifact/org.jboss.arquillian.container/arquillian-tomcat-managed-8

Can the released version be pushed to Maven central?

**Comment by rhusar** [comment]
This is fine now since we have been syncing to maven central. You can now find the 1.1.0.Final among others on central - https://mvnrepository.com/artifact/org.jboss.arquillian.container/arquillian-tomcat-managed-8

**Comment by rhusar** [comment]
Anyway, thanks for pointing this out @arjantijms !

**Comment by arjantijms** [comment]
Thanks for the update :)
