### ISSUE TITLE
Add support for configuring JarScanFilter

### ISSUE THREAD

**Issue by jansohn** [arquillian/arquillian-container-tomcat#187]
##### Issue Overview

I'd like to configure the JarScanFilter to improve start-up time of the embedded instance.

##### Expected Behaviour
Configuration options to configure JarScanFilter attributes like `tldSkip` / `tldScan`.

##### Current Behaviour
Default JarScanFilter is always applied which scans a lot of unnecessary JAR files slowing down the start-up of the embedded instance.

##### Steps To Reproduce
1. simply fire up an embedded Tomcat instance
2. Find output like the following:

    Oct 18, 2024 2:17:22 PM org.apache.jasper.servlet.TldScanner scanJars
    INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

##### Additional Information
Tomcat documentation about the feature: https://tomcat.apache.org/tomcat-10.0-doc/config/jar-scan-filter.html

**Comment by rhusar** [comment]
@jansohn Sounds good to me. Is this something you can contribute?

**Comment by jansohn** [comment]
I can try to give a crack at it next week. Feel free to take over though if you are keen.

**Comment by jansohn** [comment]
I managed to configure the `JarScanFilter` in `src/main/webapp/META-INF/context.xml`:

    <Context>
      <JarScanner>
        <JarScanFilter tldSkip="*.jar" tldScan="dummy.jar" />
      </JarScanner>
    </Context>

This is sufficient for me, so I don't think we need any additional configuration parameters in this library.

**Comment by rhusar** [comment]
@jansohn Excellent, makes sense!
