### ISSUE TITLE
Tomcat 7 managed NPE

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-container-tomcat#31]
If you set catalinaHome in arquillian.xml to your tomcat installation, you need to set catalinaBase as well. If not a NPE is thrown since in TomcatManagedContainer is executed next line, and CATALINA_BASE is not set.

```
final String absoluteCatalinaBasePath = new File(CATALINA_BASE).getAbsolutePath();
```

I think that we could modify this so in case catalinaHome property is set in arquillian.xml but system property not set to CATALINA_BASE, then CATALINA_BASE could be directly the value set in catalinaHome arquillian property.

**Comment by rhusar** [comment]
Thanks for the report @lordofthejars, upon triage this has been fixed a while ago simply as you suggested

```java
            if (CATALINA_BASE == null) {
                CATALINA_BASE = CATALINA_HOME;
            }
```

Closing as resolved.
