### ISSUE TITLE
JVM is terminated due to unsupported configuration flag -Djava.endorsed.dirs (≥ JDK 9)

### ISSUE THREAD

**Issue by tasso94** [arquillian/arquillian-container-tomcat#40]
Hi,

starting from Java 9 and onwards the [JVM configuration flag `java.endorsed.dirs` was removed](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-8E83E51A-88A3-4E9A-8E2A-66E1D66A966C). This configuration flag is currently used for the [Tomcat container](https://github.com/arquillian/arquillian-container-tomcat/blob/master/tomcat-managed-common/src/main/java/org/jboss/arquillian/container/tomcat/managed/TomcatManagedContainer.java#L150) and causes the JVM to terminate with the following message:
```
$JAVA_HOME/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Cheers,
Tassilo

**Comment by zhfeng** [comment]
Hi Tassilo,

I just raise https://issues.jboss.org/browse/ARQ-2191 and have the PR https://github.com/arquillian/arquillian-container-tomcat/pull/41

can you test with my fix ?

Thanks,
Amos

**Comment by bartoszmajsak** [comment]
Fixed by https://github.com/arquillian/arquillian-container-tomcat/pull/41
