### ISSUE TITLE
Update Weld 5 version, re-add tests

### ISSUE THREAD

**Issue by manovotn** [arquillian/arquillian-container-tomcat#89]
As part of https://github.com/arquillian/arquillian-container-tomcat/pull/87 we need to set Weld 4 version to Weld 3 just to be able to compile and build. This also requires us to temporarily remove `Tomcat10EmbeddedInContainerIT` which I could only test with snapshots. 

We should update to Weld 4 Alpha4 once it is out.
The linked PR contains a separate commit which removes the test - we can revert that one to easily bring back the test.

**Comment by manovotn** [comment]
@starksm64 this issue mentions re-adding a removed test (https://github.com/arquillian/arquillian-container-tomcat/pull/87/commits/1f464c901b6b7b24997ede0116c98c23f6f17397).
This is not something I did as part of my PR

**Comment by starksm64** [comment]
I was just closing this as out of date because of Weld 4 ref. I have reopened with issue referring to Weld 5.

**Comment by manovotn** [comment]
I see. Well, reverting that one commit should in theory do the trick, the rest is already done.
